Create 1D NumPy array

In [1]:
import numpy as np

arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Calculate the sum, mean, median, and standard deviation using build-in function

In [2]:
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))

Sum: 210
Mean: 10.5
Median: 10.5
Std Dev: 5.766281297335398


Find the indices of elements greater than 10

In [3]:
indices = np.where(arr > 10)
print("Indices:", indices)

Indices: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


create 2D NumPy array of shape 4 X 4

In [4]:
arr2 = np.arange(1, 17).reshape(4, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


taking out transpose

In [5]:
print("Transpose:\n", arr2.T)

Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


row-wise and column-wise sums

In [6]:
print("Row-wise sum:", np.sum(arr2, axis=1))
print("Column-wise sum:", np.sum(arr2, axis=0))

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


Create two 3 X 3 arrays

In [7]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

print("A:\n", a)
print("B:\n", b)

A:
 [[ 1 11  3]
 [15  5 12]
 [ 6 12  9]]
B:
 [[20  3 10]
 [18  1 17]
 [17  2  6]]


addition, subtraction, and multiplication of two 2D array

In [8]:
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)

Addition:
 [[21 14 13]
 [33  6 29]
 [23 14 15]]
Subtraction:
 [[-19   8  -7]
 [ -3   4  -5]
 [-11  10   3]]
Multiplication:
 [[ 20  33  30]
 [270   5 204]
 [102  24  54]]


dot product of the two arrays

In [9]:
print("Dot Product:\n", np.dot(a, b))

Dot Product:
 [[269  20 215]
 [594  74 307]
 [489  48 318]]


Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [10]:
arr3 = np.arange(1, 13).reshape(3, 4)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


slice the first two rows and last two columns

In [11]:
slice_part = arr3[:2, 2:]
print(slice_part)

[[3 4]
 [7 8]]
